name: SuperQA Protect

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  superqa-protect:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    
    steps:
    - name: Analyze changes and run affected tests
      id: superqa
      uses: SuperQA-ai/superqa-githubaction@main
      with:
        api_key: "az-64fedc88120d2ad481f2b36463a80f7f"
        project_name: "Nova SuperQA"
        test_plan_name: "nova superqa login - Smoke Test Plan"
        environment_name: "staging"
        mode: protect
        

    - name: Show SuperQA result
      if: always()
      env:
        RESULT: ${{ steps.superqa.outputs.test_result }}
        REPORT_URL: ${{ steps.superqa.outputs.report_url }}
      run: |
        echo "Result: $RESULT"
        echo "Report: $REPORT_URL"
